#ifndef INC_2024_I_AV_TEENSY_CONFIG_HPP
#define INC_2024_I_AV_TEENSY_CONFIG_HPP

#define CALIBRATION_DURATION_MS 0
#define ASCENT_DURATION_MS 1
#define HOVERING_DURATION_MS 0
#define DESCENT_DURATION_MS 0

#endif /*INC_2024_I_AV_TEENSY_CONFIG_HPP*/